### PR TITLE
Fixes unquoted resource title WARNING

### PR DESCRIPTION
**Pull request by blindsey**

### CODE REVIEW

**Comment by blindsey** [comment]
As long as it works I don't have a preference for Worker or Part. My patched version works fine for us since we don't use any case statements with default.

**Comment by blindsey** [comment]
What's the status on this fix?

**Comment by santana** [comment]
I'm implementing it as a worker this weekend.

**Comment by santana** [comment]
the new worker is in branch unquotedtitles and has passed my tests; @blindsey do you mind giving it a try?

**Comment by santana** [comment]
I've run more tests and the changes have passed them all. I'm moving them to master.

**Pull request closed without merging**
