### PR TITLE
puppet 2.7.11 should be a mandatory requirement

### PR DESCRIPTION
**Pull request by blindsey**

### CODE REVIEW

**Comment by santana** [comment]
I just found out that it also works with puppet 2.7.18.

If the third number has been used for maintenance, then puppet-cleaner should work on 2.7.x. I'll try to infer that from the git history.

Meanwhile, it would be nice if people can share their version of puppet where puppet-cleaner has worked fine.

**Comment by blindsey** [comment]
Yes, the tilda operator '~>' means approximately greater than which will work up to 2.8

**Comment by santana** [comment]
oh, I was talking about puppet-cleaner :) it works on puppet 2.7.18. I've run some tests and it seems to work on puppet 3 as well (see branch p3.)

**Comment by blindsey** [comment]
i was talking about puppet-cleaner as well. 2.7 <= version < 2.8

**Comment by santana** [comment]
since puppet-cleaner works with puppet 2.7 and above (including version 3) we don't need to be that specific

**Pull request closed without merging**
