### PR TITLE
Found a small problem in the order of your requires

### PR DESCRIPTION
**Pull request by blindsey**
workers/worker.rb defines the class that the worker inherit from. your glob didn't work on my mac.

### CODE REVIEW

**Comment by santana** [comment]
Thanks blindsey for the report!

Even though your patch is clearly a lot shorter than mine, I think I made a mistake by misplacing the Worker class so I'm fixing the issue you kindly report like this:

https://github.com/santana/puppet-cleaner/commit/162778dc98f3bf13b23ac58551b95f5139fde926 

Does that work for you?

**Comment by blindsey** [comment]
Sure, whatever is clever.

**Comment by santana** [comment]
Great, the patch has been applied to master. Thanks again for letting me know about this issue.

**Comment by blindsey** [comment]
ruby purists would say that classes should be kept in an autoloader friendly directory structure.

**Pull request closed without merging**
